# arducam_navigation

camera_script.py still under development!
Currently experiences occasional USB_DATA_LEN_ERRORs when calling self.odo.process() -> if calls to self.odo.process() is prevented then 
program runs fine with only couple of errors occurring after switch 1 (re-run program) is pressed.
